server:
  port: 8085
spring:
  application:
    name: Config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SoumyaMaharana-JavaFullStack/microservice-config
          clone-on-start: true
