spring:
   application:
         name: Config-Default

eureka:
   client:
   register-with-eureka: false
eureka:
  client:
  fetch-registry: false
  service-url:
     defaultZone: http://localhost:8761/eureka


